development:
  instagram_redirect_callback: http://localhost:3000/auth/instagram/callback
test:
  instagram_redirect_callback: http://localhost:3000/auth/instagram/callback
production:
  instagram_redirect_callback: http://w-instagram.herokuapp.com/auth/instagram/callback