development:
  adapter: postgresql
  database: w_instagram_development
  host: localhost
  pool: 5
  username: postgres
  password: abc123

production:
  adapter: postgresql
  database: w_instagram_search
  host: localhost
  pool: 5

test:
  adapter: postgresql
  database: w_instagram_test
  host: localhost
  pool: 5
  username: postgres
  password: abc123